
map $http_upgrade $connection_upgrade {
  default upgrade;
  '' close;
}

server {
    listen              443 ssl;
    server_name         127.0.0.1;
    ssl_certificate     /etc/nginx/conf.d/certificados/cert;
    ssl_certificate_key /etc/nginx/conf.d/certificados/key;
    root /usr/share/nginx/html;

    location / {
          root /usr/share/nginx/html;
          index index.html;
          try_files $uri $uri/ /index.html =404;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

}
